language: python

python:
  - '3.5'

before_install: cd web

install:
  - curl -o swagger https://github.com/go-swagger/go-swagger/releases/download/0.6.0/swagger_linux_amd64
  - chmod +x ./swagger

script:
  - python3 manage.py test -v 2
  - ./swagger validate ../game-engine/swagger.yaml

deploy:
  provider: cloudfoundry
  edge: true
  skip_cleanup: true
  api: https://api.run.pivotal.io
  username: adrian.moreno@emc.com
  password:
    secure: PgvpL+9MqarcBk4TUTZlyi4RbBfw6hmC6btM/5yPak97Z/TyvAmFpp92Dmkus1Jr+mgberFTc8GzxCsZFUNU/0m/rEW6fsHRXFhMVA/FT0FeTf72NSoPRhHqKRROLCNFvuxUb6DkL+pGkGewaEJbLHBT3v2VO5efqNKM9jRRjIjnzyzKOz1u0v1cA19o1hSKvNi1VXSosi/YYPIGmn6Ij11Cx36SUVQPp12r/r47KzLDik/9gq0Uxc4GpXKcBH1miEHGJXlpcIcI9y26r/2CcZ28KW95z25YBpcK7zwyPIAGmUkjqsovGNt/nbktG118ShfPdONpeX/+qYRbiLk07HRKArxOX8zrmIwI0FnjQoKqNvV7R6o05xHFeitbnFvNNx2GrPuK6qvgPnn51bKyYzpFnc+dfgK9t//AEJ6+5scTxC8zWjJtsvB01y0UDtkJDeZryJsJ5vhgMPM9a0IkR5b4BeYoPlXAiMVEMpfqgCehK1pNAM2oAqUNcbus8N3q9oPI4yseu1AUwnfrDtN0haTXQN4abVfxrGPbp6S9p9FAUcCYvesaH3aGUUOPNzOymsqdp4zAPsXViadF3nL4undretk0ZTt3ZAJ8+xIR8pkPIftB01nn16o7TPB/1gZvbzZMoocKR2rCFHeGRO6uxIDOGd6YgAzwEwthpWApan4=
  organization: vxrackneutrino
  space: development
  on:
    repo: VxRackNeutrino/Hero
    branch: develop
