language: python

python:
  - "3.5"

before_install: cd web

script:
  - python3 manage.py test -v 2

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy_cf.sh
  on:
    branch: develop
