version: '2'
services:
  engine:
    image: "emccorp/hero-engine"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=titanuser:Neutrin0R0cks!@tcp(db:3306)/titandb
      - ADMIN_TOKEN=1234
    links:
      - db
    command: ./wait-for-it.sh -t 60 db:3306 -- app
  web:
    image: "emccorp/hero-web"
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=mysql://titanuser:Neutrin0R0cks!@db:3306/titandb
      - HERO_API=http://engine:8080
      - HERO_ADMIN_TOKEN=1234
    links:
      - db
      - engine
    command: ./wait-for-it.sh -t 60 db:3306 -- gunicorn hero.wsgi -b 0.0.0.0:8080 --log-file -
  db:
    image: "emccorp/hero-db"
    environment:
      - MYSQL_ROOT_PASSWORD=root
