version: '2'
services: 
  game-engine:
    image: "emccorp/hero-engine"
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=root:root@/titandb
  db:
    image: "emccorp/hero-db"
    environment:
      - datavol=/data

