version: '2'
services:
  engine:
    image: "emccorp/hero-engine"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=titanuser:Neutrin0R0cks!@tcp(db:3306)/titandb
    links:
      - db
  web:
    image: "emccorp/hero-web"
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=mysql://titanuser:Neutrin0R0cks!@db:3306/titandb
    links:
      - db
  db:
    image: "emccorp/hero-db"
    environment:
      - MYSQL_ROOT_PASSWORD=root
