heat_template_version: 2015-10-15

description: > 
  This template creates entities needed for creating VMs

parameters:
  dns_servers:
    type: comma_delimited_list
    description: comma delimited dns servers, e.g., [10.0.0.1,10.0.0.2]

  public_network:
    type: string
    description: public network name or id

  prefix:
    type: string
    description: prefix for openstack objects

  image_id:
    type: string
    description: image name or id

  image_location: 
    type: string
    description: image location

resources:

  private_network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: 
        list_join: ['-', [{get_param: prefix}, 'network']]

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: 
        list_join: ['-', [{get_param: prefix}, 'subnet']]
      cidr: 10.30.20.0/24
      enable_dhcp: true
      network: {get_resource: private_network}
      dns_nameservers: { get_param: dns_servers } 

  private_router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      name: 
        list_join: ['-', [{get_param: prefix}, 'router']]
      external_gateway_info: {network : {get_param: public_network}} 

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: private_router}
      subnet: {get_resource: private_subnet}

  image:
    type: OS::Glance::Image
    properties:
      container_format: bare
      disk_format: qcow2
      location: {get_param: image_location}
      name: {get_param: image_id}

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: 
        list_join: ['-', [{get_param: prefix}, 'secgroup']]
      rules:
      - protocol: icmp
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 22
        port_range_max: 22
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 80
        port_range_max: 80
      - protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 443
        port_range_max: 443

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        list_join: ['-', [{get_param: prefix}, 'keypair']]
      public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChOM5BQiPlSOr311orrJYeyqsgx2qg+LKivyqpSj8XhjV9Hd8V1TXTj/eiQ6Tq++FwwcdOLgkU2BOFHvdJRR78p8TTQaqmNX/4S/xRNJi3DLE4wcw/MRPdcwJk1F1rIlQFPVOfvW5tpi2iK7pZbfUvBTNqjTbaERw4DvnsWGGfjORc9XZ/4RcVnyLzdlPbTHgIZtUGdxiMsTT88GfBKjqdeZK5E/1MSCVkXWbVFawSYvUI83T4EbVrovRFkPldcaaQw/iUb3EL9WcPjSRscosu7OAJnQR4jP/UhsEztVHDAkcxouImk9JAR/V/Cn3RWPFGumzRG9sm4k4z9HT/8EUl
